version: "3.9"
services:
  tailscale:
    image: tailscale-sidecar-proxy
    environment:
      TAILSCALE_AUTH_KEY: ${TAILSCALE_AUTH_KEY:?err}
      TAILSCALE_HOSTNAME: test-service
      TAILSCALE_FUNNEL: false
      TAILSCALE_SERVE_PORT: 80
    volumes:
      - /var/lib/tailscale_state/
  example-service:
    image: nginxdemos/hello
    network_mode: service:tailscale
